name: 'fly-deploy'
description: 'Deploys to fly.io'
inputs:
  workspace_name:
    required: false
    description: "The name of the workspace to deploy. This is used to find the folder of the workspace by searching name fields in all package.json files."
  use_isolated_workspace:
    required: false
    description: "Whether to set the current working directory to the found workspace path. Defaults to false. You only need to change this if you want to deploy a folder in isolation and dont need any of the other workspaces. For monorepos keep this should as false."
    default: "false"
  app_name:
    required: false
    description: "The name of the fly app to deploy."
  config_file_path:
    required: false
    description: "Relative workspace path of the fly config file. Defaults to './fly.toml'"
    default: "./fly.toml"
  attach_consul:
    required: false
    description: "Whether to attach a consul cluster to the app, for instance if you want to use SQLite with litefs. Defaults to false"
    default: "false"
  attach_postgres:
    required: false
    default: "false"
    description: "Boolean string (true|false) to indicate whether to attach a postgres cluster to the app. Make sure to set FLY_REGION, otherwise the postgres cluster creation will fail."
  attach_existing_postgres:
    required: false
    description: "Name of an existing postgres cluster to attach to the app. The action will not create it for you if it doesnt exist - If you want to create it, use the 'attach_postgres' action input instead."
  secrets:
    required: false
    description: "A list of secrets to set on the fly app. The format is 'key=value', newline separated. You can use this to set secrets on the fly app."
  env_vars:
    required: false
    description: "A list of non-secret plain-text environment variables to set on the fly app. The format is 'key=value', newline separated. You can use this to set non-secret environment variables on the fly app."
  build_args:
    required: false
    description: "A list of build args (--build-arg). Those are passed to the flyctl deploy command, which passes them to the docker build command. The format is 'key=value', newline separated."
  build_secrets:
    required: false
    description: "A list of secrets to set on the fly app. The format is 'key=value', newline separated. You can use this to set secrets available to the docker build command, only available during the build phase."
  private:
    required: false
    description: "Boolean string (true|false) to indicate whether to enable flycast and only add a private IPv6 address to the app. Defaults to false."
    default: "false"
outputs:
  app_name:
    description: "The name of the fly app that was deployed."
  app_url:
    description: "The URL of the fly app that was deployed."
  app_hostname:
    description: "The hostname of the fly app that was deployed."
  app_id:
    description: "The ID of the fly app that was deployed."
  machine_names:
    description: "The names of the machines that were deployed."
  machine_ids:
    description: "The IDs of the machines that were deployed."
  public_ips:
    description: "The public IPs of the app."
  private_ips:
    description: "The private IPs of app."
  postgres_cluster_name:
    description: "The name of the postgres cluster app that was deployed."
  workspace_name:
    description: "The name of the workspace that was deployed."
  workspace_path:
    description: "The relative path of the workspace that was deployed."
runs:
  using: 'docker'
  image: 'Dockerfile'
