name: 'fly-deploy'
description: 'Deploys to fly.io'
inputs:
  app_name_prefix:
    required: false
    description: "A prefix for the fly app name. This is useful if you want to use automatic app_name generation based on the workspace name, but want to add a prefix to the app name (like $GITHUB_REPOSITORY_OWNER)"
  app_name:
    required: false
    description: "The name of the fly app to deploy. If not set, the app name is generated based on the workspace name and the app_name_prefix and app_name_suffix inputs. If set, this overrides the automatic app name generation and prefix/suffix inputs are ignored."
  app_name_suffix:
    required: false
    description: "A suffix for the fly app name. This is useful if you want to use the automatic app_name generation based on the workspace name, but want to add a suffix to the app name (like 'production', 'pre-production', 'preview', etc.)"
  config_file_path:
    required: false
    description: "Relative workspace path of the fly config file. Defaults to './fly.toml'"
    default: "./fly.toml"
  secrets:
    required: false
    description: "A list of secrets to set on the fly app. The format is 'key=value', newline separated. You can use this to set secrets on the fly app."
  env_vars:
    required: false
    description: "A list of non-secret plain-text environment variables to set on the fly app. The format is 'key=value', newline separated. You can use this to set non-secret environment variables on the fly app."
  build_args:
    required: false
    description: "A list of build args (--build-arg). Those are passed to the flyctl deploy command, which passes them to the docker build command. The format is 'key=value', newline separated."
  build_secrets:
    required: false
    description: "A list of secrets to set on the fly app. The format is 'key=value', newline separated. You can use this to set secrets available to the docker build command, only available during the build phase."
  workspace_name:
    required: false
    description: "The name of the workspace to deploy. This is used to find the folder of the workspace by searching the 'name' field in all package.json files recursively. Defaults to the 'name' in of the package.json found in the repository root."
  use_isolated_workspace:
    required: false
    description: "Whether to set the current working directory to the found workspace path. Defaults to false. You only need to change this if you want to deploy a folder in isolation and dont need any of the other workspaces. For monorepos keep this should as false."
    default: "false"
  attach_consul:
    required: false
    description: "Whether to attach a consul cluster to the app, for instance if you want to use SQLite with litefs. Defaults to false"
    default: "false"
  private:
    required: false
    description: "Boolean string (true|false) to indicate whether to enable flycast and only add a private IPv6 address to the app. Defaults to false."
    default: "false"
outputs:
  app_name:
    description: "The name of the fly app that was deployed."
  app_url:
    description: "The URL of the fly app that was deployed."
  app_hostname:
    description: "The hostname of the fly app that was deployed."
  app_id:
    description: "The ID of the fly app that was deployed."
  machine_names:
    description: "The names of the machines that were deployed."
  machine_ids:
    description: "The IDs of the machines that were deployed."
  public_ips:
    description: "The public IPs of the app."
  private_ips:
    description: "The private IPs of app."
  workspace_name:
    description: "The name of the workspace that was deployed."
  workspace_path:
    description: "The relative path of the workspace that was deployed."
runs:
  using: 'docker'
  image: 'Dockerfile'
